version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-cli: circleci/aws-cli@0.1.11

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run coverage
          command: pytest --cov=.
      - run:
          name: Run linting
          command: flake8
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t marcout/lettings_site:$CIRCLE_SHA1 .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker push marcout/lettings_site:$CIRCLE_SHA1
  deploy:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
        command: |
          sudo apt update
          sudo apt -y --qq install awscli
      - aws-cli/configure
      - run:
        command: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f9r8d7r0
          docker tag marcout/lettings-app:latest public.ecr.aws/f9r8d7r0/lettings-app:$CIRCLE_SHA1
          docker push public.ecr.aws/f9r8d7r0/lettings-app:latest
      
          

workflows:
  test-the-application:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: master
 
  deploy-the-application:
    jobs:
      - build-and-test
      - deploy:
          filters:
            branches:
              only: master



