version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-cli : circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.1
  aws-ecs: circleci/aws-ecs@3.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run coverage
          command: pytest --cov=.
      - run:
          name: Run linting
          command: flake8
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t marcout/lettings_site:$CIRCLE_SHA1 .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker push marcout/lettings_site:$CIRCLE_SHA1
  deploy:
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          region: AWS_REGION
          registry-id: AWS_ECR_REGISTRY_ID
          repo: ${MY_APP_PREFIX}
          tag: ${CIRCLE_SHA1}
      - aws-ecs/deploy-service-update:
          cluster: ${MY_APP_PREFIX}-cluster
          container-image-name-updates: container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}
          family: ${MY_APP_PREFIX}-service
          requires:
            - aws-ecr/build-and-push-image
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Configure AWS CLI
          command: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set default.region $AWS_REGION
      - run:
          name: Push Docker image to ECR Public
          command: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f9r8d7r0
            docker tag marcout/lettings-app:latest public.ecr.aws/f9r8d7r0/lettings-app:$CIRCLE_SHA1
            docker push public.ecr.aws/f9r8d7r0/lettings-app:latest

workflows:
  version: 2
  test-the-application:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: master
 
  deploy-the-application:
    jobs:
      - build-and-test
      - deploy:
          filters:
            branches:
              only: master
