version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linting
          command: flake8

  deploy:
    executor: aws-cli/default
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run:
          name: Connect to EC2
          command: |
            echo "$SSH_PRIVATE_KEY" > Lettings.pem
            chmod 600 Lettings.pem
            ssh -o StrictHostKeyChecking=yes -i "Lettings.pem" ec2-user@ec2-3-252-160-237.eu-west-1.compute.amazonaws.com
      - run:
          name: Test SSH Connection
          command: |
            ssh ec2-instance 'echo "SSH connection successful"'
      - run:
          name: Create release and notify Sentry of deploy
          command: |
            export SENTRY_ENVIRONMENT=production
            curl -sL https://sentry.io/get-cli/ | bash
            export SENTRY_RELEASE=$(sentry-cli releases propose-version)
            sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
            sentry-cli releases set-commits $SENTRY_RELEASE --auto
            sentry-cli releases finalize $SENTRY_RELEASE
            sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
            sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE --log-level=debug


workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

  master-workflow:
    jobs:
      - deploy
