version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run coverage
          command: pytest --cov=.

      - run:
          name: Run linting
          command: flake8


  deploy:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          echo deploy
workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: master
      - deploy:
          
      - azure/build-and-push-image:
          requires:
            - build-and-test
          login-server-name: docker.io
          registry-name: docker.io
          repo: docker.io
          filters:
            branches:
              only: master
