version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
        pkg-manager: pip
        
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest

workflows:
  sample:
    jobs:
      - test
