version: 2.1

jobs:
  test-azure-connection:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - run:
          name: Connect to Azure
          command: |
            az login --username $AZURE_USERNAME --password $AZURE_PASSWORD

      - run:
          name: Test Azure connection
          command: |
            az account show

workflows:
  version: 2
  test-azure-connection:
    jobs:
      - test-azure-connection
