version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:

    docker:
      - image: cimg/python:3.7

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          
      - run:
          name: Run linting
          command: flake8
 
      - run:
          name: Run coverage
          command: pytest --cov=.
          
  deploy:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          echo deploy


workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
