version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install pytest
          command: pip install pytest-django
      - run:
          name: Run linting
          command: flake8
      - run:
          name: Run test
          command: pytest

  deploy:
    executor: aws-cli/default
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "n0n70ug5nLlO+RIpqp4T3Ey3/Px/a862Tnl5/iqCbk0"
      - run:
          name: Build Docker image
          command: |
            SHA1="$CIRCLE_SHA1"
            docker build -t marcout/lettings-app .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker tag marcout/lettings-app:latest marcout/lettings-app:"$SHA1"
            docker push marcout/lettings-app:"$SHA1"
      - run:
          name: Pull Docker image
          command: |
            SHA1="$CIRCLE_SHA1"
            docker pull marcout/lettings-app:"$SHA1"
      - run:
          name: Add key on known hosts
          command: ssh-keyscan -H -t ed25519 ec2-52-212-209-10.eu-west-1.compute.amazonaws.com >> ~/.ssh/known_hosts
      - run:
          name: Connect to EC2 and pull image docker
          command: |
            SHA1="$CIRCLE_SHA1"
            echo "$SSH_PRIVATE_KEY" > Lettings.pem
            chmod 600 Lettings.pem
            ssh -i "Lettings.pem" ec2-user@ec2-52-212-209-10.eu-west-1.compute.amazonaws.com docker pull marcout/lettings-app:"$SHA1"
      - run: 
          name: Copy .env from EC2
          command: |
            scp -i "Lettings.pem" ec2-user@ec2-52-212-209-10.eu-west-1.compute.amazonaws.com:/home/ec2-user/.env .
      - run:
          name: stop container
          command: |
            ssh -i "Lettings.pem" ec2-user@ec2-52-212-209-10.eu-west-1.compute.amazonaws.com docker ps -aq
            ssh -i "Lettings.pem" ec2-user@ec2-52-212-209-10.eu-west-1.compute.amazonaws.com "sudo pkill -f :8000"
      - run:
          name: run docker image
          command: |
            SHA1="$CIRCLE_SHA1"
            ssh -i "Lettings.pem" ec2-user@ec2-52-212-209-10.eu-west-1.compute.amazonaws.com docker run -d -p 8000:8000 -e SENTRY_DSN=$SENTRY_DSN -e SECRET_KEY=$SECRET_KEY marcout/lettings-app:"$SHA1"
      - run:
          name: Create release and notify Sentry of deploy
          command: |
            export SENTRY_ENVIRONMENT=production
            curl -sL https://sentry.io/get-cli/ | bash
            export SENTRY_RELEASE=$(sentry-cli releases propose-version)
            sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
            sentry-cli releases set-commits $SENTRY_RELEASE --auto
            sentry-cli releases finalize $SENTRY_RELEASE
            sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
            sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE --log-level=debug


workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

  master-workflow:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
