version: 2.1

jobs:
  test:
    docker:
      - image: python:3.7
    working_directory: ~/project
    environment:
      - DJANGO_SETTINGS_MODULE: oc_lettings_site.settings
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python manage.py pytest

workflows:
  version: 2.1
  test-the-application:
    jobs:
      - test
